### ISSUE TITLE
Blank node for crm:P1_is_identified_by

### ISSUE THREAD

**Issue by workergnome** [american-art/acm#10]
see http://data.americanartcollaborative.org/page/acm/object/002_lc_s6.  This should not be  a blank node.

**Comment by VladimirAlexiev** [comment]
Same for http://data.americanartcollaborative.org/page/acm/object/1980_49 (Great Red Tailed Hawk)

**Comment by bsnikhila** [comment]
Fixed.

**Comment by workergnome** [comment]
Confirmed fixed.
