### ISSUE TITLE
remove obsolete ACM files

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/acm#11]
@KatherineMoloney: Please check Github and remove obsolete input files (or tell us which ones to remove).
Eg there are have 3 copies of ExhibitionData:
- data-upload\AAC_AmonCarter_ExhibitionData.xml
- ExhibitionCatalogData\AAC_AmonCarter_ExhibitionData.xml
- ExhibitionData\AAC_AmonCarter_ExhibitionData.xml

No wonder the mixup in #5 happened. cc @bsnikhila

**Comment by VladimirAlexiev** [comment]
@bsnikhila: there is also duplication for the output data, eg acm-objects vs ObjectData are nearly the same. Please remove the obsolete directories

**Comment by KatherineMoloney** [comment]
•	The correct object data file is AAC_AmonCarter_ObjectData_Updated_URIs.xml 
•	Apparently I do not have permission to delete files. Please delete earlier files.
•	ExhibitionCatalogData\AAC_AmonCarter_ExhibitionData.xml and the ExhibitionData\AAC_AmonCarter_ExhibitionData.xml are two different data sets. One refers to the exhibitions and the other refers to catalogs associated with those exhibitions. 
•	I came into this project last May so I wasn’t involved in data uploads to that point. My technological expertise is limited so at best I can see the difference between data sets. I’m best-guessing that the last upload is the correct one. 
I’m not trying to be unhelpful, I honestly just don’t know.

**Comment by VladimirAlexiev** [comment]
I see what happened. The person doing the conversion took the 4 source files in data-upload and copied them all over the place. Eg 
- data-upload/AAC_AmonCarter_ObjectData.xml is copied to 
- ObjectData/AAC_AmonCarter_ObjectData.xml and also to
- acm-objects/acm-objects.xml

Copying files, just like copying source code, is a capital offence in IT, because it creates maintenance problems (cc @caknoblock)
- Now that we got AAC_AmonCarter_ObjectData_Updated_URIs.xml, where should it be copied?
- How is one to know which is the latest version of the source files?

Please leave only ONE copy of each file. Use it in its original location, or make symbolic links.

**Comment by bsnikhila** [comment]
I removed all old files and old models.
