### ISSUE TITLE
Object and actor data not mapping together

### ISSUE THREAD

**Issue by KatherineMoloney** [american-art/acm#13]
I see that the acm's data is not mapping the same way as other institutions, i.e. the object link doesn't include the actor information as the others do. Where is the disconnect here?

**Comment by caknoblock** [comment]
The mapping of every institution is different based on the way the raw data is organized.  There does not seem to be any issue with the object links to actors.  If you go to review.americanartcollaborative.org <http://review.americanartcollaborative.org/>, go to the review of objects, enter of the ACM objects (http://data.americanartcollaborative.org/acm/object/1980_51 <http://data.americanartcollaborative.org/acm/object/1980_51>), and ask for the artist, it does produce the correct artist for this object.
