### ISSUE TITLE
Current Owner Not Mapped

### ISSUE THREAD

**Issue by kateblanch** [american-art/acm#17]
Current owner value was hand-mapped by ISI (because the museums did not add their name to every item in their collection, explicitly). ACM seems to have been missed. This will need to prioritized for fix in August. 

Related to closed issue : https://github.com/american-art/aac_mappings/issues/66

**Comment by cbutcosk** [comment]
This issue has changed shape, but is still open: now ACM objects carry an owner of `<http://data.americanartcollaborative.org/acm/data.americanartcollaborative.org/acm>` in the triplestore.

**Comment by bsnikhila** [comment]
Fixed it.
