### ISSUE TITLE
Object doesn't have triples 

### ISSUE THREAD

**Issue by KatherineMoloney** [american-art/acm#19]
ACM object 1999.17 has the following data:

<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P1_is_identified_by>   <http://data.americanartcollaborative.org/acm/object/17_1999/acc_no> .
--
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P102_has_title>   <http://data.americanartcollaborative.org/acm/object/17_1999/lassoingwildhorses>   .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P108i_was_produced_by>   <http://data.americanartcollaborative.org/acm/object/17_1999/production>   .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P41i_was_classified_by>   <http://data.americanartcollaborative.org/acm/object/17_1999/classification>   .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P52_has_current_owner>   <http://data.americanartcollaborative.org/acm/data.americanartcollaborative.org/acm>   .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.cidoc-crm.org/cidoc-crm/P67i_is_referred_to_by>   <http://data.americanartcollaborative.org/acm/object/17_1999/medium> .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>   <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object> .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://www.w3.org/2000/01/rdf-schema#label> "Lassoing Wild   Horses" .
<http://data.americanartcollaborative.org/acm/object/17_1999>   <http://xmlns.com/foaf/0.1/homepage>   <http://www.cartermuseum.org/imu/acm/#details=ecatalogue.96722> .

There are no triples to support these URIs. This is the only object that didn't have the triples in the data set! Congratulations on a job well done.

**Comment by bsnikhila** [comment]
Could you please tell me what you mean by this object does not have triples?

**Comment by KatherineMoloney** [comment]
Excuse my stupid error. Somehow some of the lines had an extra character and they sorted differently in the spreadsheet I was reviewing. Geez that's embarrassing. But at least it's an issue you don't have to work on!
