### ISSUE TITLE
Websites do not follow the model

### ISSUE THREAD

**Issue by workergnome** [american-art/acm#8]
Given <http://data.americanartcollaborative.org/page/acm/object/002_lc_s6>, the webpage itself should be the URI of the foaf:homepage, not http://data.americanartcollaborative.org/page/acm/object/002_lc_s6/uri

Currently you have the URI as a label for the document, which is not correct.

**Comment by bsnikhila** [comment]
This is fixed.

**Comment by workergnome** [comment]
So it is.
