### ISSUE TITLE
Websites URIs are not correct

### ISSUE THREAD

**Issue by workergnome** [american-art/acm#9]
http://data.americanartcollaborative.org/page/acm/object/002_lc_s6/uri has the label "http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.35260]", but (even after solving issue #8), that URI should be http://www.cartermuseum.org/imu/acm/#details=ecatalogue.35260.

Is this a data issue, or a mapping issue?

**Comment by VladimirAlexiev** [comment]
Right. Eg
http://data.americanartcollaborative.org/page/acm/object/1980_49 should have
foaf:homepage http://www.cartermuseum.org/imu/acm/#details=ecatalogue.132522

**Comment by bsnikhila** [comment]
Fixed.

**Comment by VladimirAlexiev** [comment]
checked, also in yasgui http://yasgui.org/short/H1C8F0U2l (label = url)
